sudo: false

language: scala
jdk:
  - oraclejdk8

env:
  - SBT_VERSION=1.1.6
  - SBT_VERSION=0.13.17

script:
  - sbt ^^$SBT_VERSION scripted

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot

before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -delete
  - find $HOME/.ivy2/cache -name "*-SNAPSHOT*" -delete
